# Generated by Django 4.2.9 on 2024-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_group',
            field=models.IntegerField(choices=[(1, 'Income'), (2, 'Spending'), (3, 'Loan')]),
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
