# Generated by Django 4.2.9 on 2024-02-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygroup',
            name='record_type',
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
