# Generated by Django 4.2.9 on 2024-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_category_group_delete_categorygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_group',
            field=models.IntegerField(choices=[(1, 'Thu tiền'), (2, 'Chi tiền'), (3, 'Vay nợ')]),
        ),
    ]
