# Generated by Django 4.2.9 on 2024-04-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
