# Generated by Django 4.2.9 on 2024-04-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_loan_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updatedAt']},
        ),
    ]
