# Generated by Django 4.2.9 on 2024-04-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_group', '-updatedAt']},
        ),
    ]
