# Generated by Django 4.2.9 on 2024-04-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledirectory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
